export { default as MainPage } from './main-page/MainPage'
export { default as LoginPage } from './login-page/LoginPage'
export { default as MapPage } from './map-page/MapPage'
export { default as NotFoundPage } from './not-found-page/NotFoundPage'
export { default as UserPage } from './user-page/UserPage'